### ISSUE TITLE
Error when running local rmq

### ISSUE THREAD

**Issue by stan-dot** [DiamondLightSource/blueapi#703] opened 2024-11-08 16:05 UTC
Just started the script to run a local rabbit message queue when got this error message:
```bash
 ##  ##      RabbitMQ 4.0.3
  ##  ##
  ##########  Copyright (c) 2007-2024 Broadcom Inc and/or its subsidiaries
  ######  ##
  ##########  Licensed under the MPL 2.0. Website: https://rabbitmq.com

  Erlang:      26.2.5.5 [jit]
  TLS Library: OpenSSL - OpenSSL 3.3.2 3 Sep 2024
  Release series support status: see https://www.rabbitmq.com/release-information

  Doc guides:  https://www.rabbitmq.com/docs
  Support:     https://www.rabbitmq.com/docs/contact
  Tutorials:   https://www.rabbitmq.com/tutorials
  Monitoring:  https://www.rabbitmq.com/docs/monitoring
  Upgrading:   https://www.rabbitmq.com/docs/upgrade

  Logs: <stdout>

  Config file(s): /etc/rabbitmq/conf.d/10-defaults.conf

  Starting broker...2024-11-08 16:03:49.493558+00:00 [info] <0.254.0> 
2024-11-08 16:03:49.493558+00:00 [info] <0.254.0>  node           : rabbit@70895a937078
2024-11-08 16:03:49.493558+00:00 [info] <0.254.0>  home dir       : /var/lib/rabbitmq
2024-11-08 16:03:49.493558+00:00 [info] <0.254.0>  config file(s) : /etc/rabbitmq/conf.d/10-defaults.conf
2024-11-08 16:03:49.493558+00:00 [info] <0.254.0>  cookie hash    : 0qpEZ+Ja9O0MuNKBqzzKDA==
2024-11-08 16:03:49.493558+00:00 [info] <0.254.0>  log(s)         : <stdout>
2024-11-08 16:03:49.493558+00:00 [info] <0.254.0>  data dir       : /var/lib/rabbitmq/mnesia/rabbit@70895a937078
2024-11-08 16:03:49.498450+00:00 [notice] <0.44.0> Application mnesia exited with reason: stopped

2024-11-08 16:03:49.498540+00:00 [error] <0.254.0> 
2024-11-08 16:03:49.498540+00:00 [error] <0.254.0> BOOT FAILED
2024-11-08 16:03:49.498540+00:00 [error] <0.254.0> ===========
2024-11-08 16:03:49.498540+00:00 [error] <0.254.0> Error during startup: {error,
2024-11-08 16:03:49.498540+00:00 [error] <0.254.0>                           {cannot_read_enabled_plugins_file,
2024-11-08 16:03:49.498540+00:00 [error] <0.254.0>                               "/etc/rabbitmq/enabled_plugins",eacces}}
2024-11-08 16:03:49.498540+00:00 [error] <0.254.0> 
BOOT FAILED
===========
Error during startup: {error,
                          {cannot_read_enabled_plugins_file,
                              "/etc/rabbitmq/enabled_plugins",eacces}}

2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>   crasher:
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     initial call: application_master:init/4
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     pid: <0.253.0>
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     registered_name: []
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     exception exit: {{cannot_read_enabled_plugins_file,
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>                          "/etc/rabbitmq/enabled_plugins",eacces},
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>                      {rabbit,start,[normal,[]]}}
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>       in function  application_master:init/4 (application_master.erl, line 142)
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     ancestors: [<0.252.0>]
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     message_queue_len: 1
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     messages: [{'EXIT',<0.254.0>,normal}]
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     links: [<0.252.0>,<0.44.0>]
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     dictionary: []
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     trap_exit: true
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     status: running
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     heap_size: 2586
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     stack_size: 28
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>     reductions: 167
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0>   neighbours:
2024-11-08 16:03:50.499987+00:00 [error] <0.253.0> 
Runtime terminating during boot (terminating)
2024-11-08 16:03:50.504439+00:00 [notice] <0.44.0> Application rabbit exited with reason: {{cannot_read_enabled_plugins_file,"/etc/rabbitmq/enabled_plugins",eacces},{rabbit,start,[normal,[]]}}

Crash dump is being written to: /var/log/rabbitmq/erl_crash.dump...done
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[os_mon] memory supervisor port (memsup): Erlang has closed

```

**Comment by stan-dot** [comment] 2024-11-08 16:05
OTOH this command works:

> podman run -it --rm --name dev-rabbitmq -p 5552:5552 -p 15672:15672 -p 5673:5673 -e RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS='-rabbitmq_stream advertised_host localhost'  rabbitmq:3.13

**Comment by stan-dot** [comment] 2024-11-08 17:13
moreover I'd like to be able to easily send mock data over the created RMQ instance

**Comment by callumforrester** [comment] 2024-11-11 10:17
Hmm, unable to reproduce locally, could you tell me more about your environment? Be aware that script will not work on RHEL7

**Comment by stan-dot** [comment] 2024-11-11 11:19
> Be aware that script will not work on RHEL7

this crucial fact might have been added in the PR...



https://github.com/DiamondLightSource/blueapi/pull/668/files

**Comment by dperl-dls** [comment] 2024-11-29 10:22
Oh, this should probably be resolved by https://github.com/DiamondLightSource/blueapi/pull/731, @stan-dot  try adding :z to the end of the bind mount, see https://devops.stackexchange.com/questions/11267/permission-denied-within-mounted-volume-inside-podman-container

**Closed** 2024-11-29 12:15 UTC
Labels: bug, cli, dev-environment
